<?php 
	//gets module version from config.xml
	$_moduleVersion=$this->getTwoFactorAuthVersion();
	//config init
	$_configLinks='default/he2falinks/'; $_config=Mage::getConfig();
	//links from translate CSV file
	$_heLink=$_config->getNode($_configLinks.'human-element-link');
	$_nexcessLink=$_config->getNode($_configLinks.'nexcess-link');
	$_docsLink=$_config->getNode($_configLinks.'docs-link');
	$_submitBugLink=$_config->getNode($_configLinks.'submit-bug-link');
	//$_multiAuthLink=$_config->getNode($_configLinks.'multi-auth-link');
	$_mageSupportLink=$_config->getNode($_configLinks.'mage-support-link');
	$_contactLink=$_config->getNode($_configLinks.'contact-link');
	
	//remove http... from start of link so it can be used as a label in the paragraph
	function simplifyLinkLabel($link){
		$link=str_replace('https://www.', '', $link);
		$link=str_replace('http://www.', '', $link);
		return $link;
	}
?>

<div class="sentry-intro">
	<div class="line">
		<?php echo $this->__('Sentry Two-Factor Authentication for Magento v%s', $_moduleVersion); ?>
	</div>
	<div class="line">
		<?php echo $this->__('Developed as a Partnership between <a href="%s" target="_blank">Human Element</a> and <a href="%s" target="_blank">Nexcess</a> Hosting',$_heLink,$_nexcessLink); ?>
	</div>
</div>
<div class="sentry-banner">
	<div class="sentry-ribbon">
		<?php echo $this->__('<strong>Sentry</strong> Two-factor Authentication for Magento'); ?>
		<div class="btns">
			<a class="btn bug" href="<?php echo $_submitBugLink; ?>" target="_blank"><?php echo $this->__('Submit a Bug'); ?></a>
			<a class="btn readme" href="<?php echo $_docsLink; ?>" target="_blank"><?php echo $this->__('Read Me'); ?></a>
		</div>
	</div>
	<p>Multifactor authentication provides an additional check when logging into your Magento administration system. 
		Once configured, an additional challenge screen is added to the admin login process. This screen will interact 
		with an additional method of contact, usually a cellphone or email, that will prove that the user attempting login is the real user.</p>
	<p>NOTE - when using multifactor authentication it is highly advised that each admin user have their own account.</p>
	<p>To find out more about Human Element and <a href="<?php echo $_mageSupportLink ?>" target="_blank">Magento Support Services</a>, please visit our website at 
		<a href="<?php echo $_heLink ?>" target="_blank"><?php echo simplifyLinkLabel($_heLink); ?></a> 
		or fill in our <a href="<?php echo $_contactLink; ?>" target="_blank">contact form</a>. 
		To find out more about Nexcess Hosting, visit their website at 
		<a href="<?php echo $_nexcessLink; ?>" target="_blank"><?php echo simplifyLinkLabel($_nexcessLink); ?></a>. </p>
</div>
